# Generated by Django 4.0.6 on 2022-07-29 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_family', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='birthday',
            field=models.DateField(default=44.22222222222222),
        ),
    ]
