# Generated by Django 4.0.6 on 2022-07-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_family', '0004_alter_family_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='birthday',
        ),
        migrations.AddField(
            model_name='family',
            name='user_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
