# Generated by Django 4.0.6 on 2022-07-29 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_family', '0005_remove_family_birthday_family_user_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='user_created',
        ),
    ]
